---
title: "Visualization_full"
author: "Zhiyi Zhu"
date: "2023-10-03"
output:github_document
---

```{r}
library(tidyverse)
library(ggridges)
```

## Get the data for the plot

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## Make a plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) +
  geom_point()
```

### Pipes and stuff

```{r}
weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

## Save ggplot objects

```{r}
ggp_nyc_weather = 
  weather_df |>
  filter(name == "CentralPark_NY") |>
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point() # dose not print something

ggp_nyc_weather #print the plot
```

## Fancy plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) +
  geom_point(aes(color = name), alpha = .3) +
  geom_smooth(se = FALSE)

```

## Plot with facet

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) +
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) +
  facet_grid(. ~name)
```















